### ISSUE TITLE
General query- How did you add "Subscribe" in your blog setup?

### ISSUE THREAD

**Issue by duttashi** [dgrtwo/dgrtwo.github.com#4]
Hello David,
I'm using the minimal mistakes theme for [my blog](https://duttashi.github.io/)
Could you advice on how did you create the "Subscribe" feature in your blog.
Thank you for your time.

Cheers
Ashish

**Comment by dgrtwo** [comment]
I added [this snippet of code](https://github.com/dgrtwo/dgrtwo.github.com/blob/f2122ace187e756f43607eaaa210c311c184bcd6/_includes/_author-bio.html#L29) to my `author-bio` include file (see [here](https://blogtrottr.com/help/#embedded_forms) for more). Good luck!

**Comment by duttashi** [comment]
will figure this out later
