### ISSUE TITLE
It seems to me that inflate function is not working properly...

### ISSUE THREAD

**Issue by statkclee** [dgrtwo/dgrtwo.github.com#7]
I could not figure out how to use inflate function properly...

When I reproduce what you implemented, I've got the following errors.

http://varianceexplained.org/r/bayesian_ab_baseball/

`two_players %>% `
`+   broom::inflate(x = seq(.28, .33, .00025)) %>%`
`+   mutate(density = dbeta(x, alpha1, beta1)) %>%`
`+   ggplot(aes(x, density, color = name)) +`
`+   geom_line() +`
`+   labs(x = "Batting average", color = "")`
`Error in mutate_impl(.data, dots) : `
`  Evaluation error: object 'alpha1' not found.`

**Comment by adamribaudo** [comment]
I don't see inflate as a function:

`> library(broom)
> broom::inflate
Error: 'inflate' is not an exported object from 'namespace:broom'`

`> ?inflate
No documentation for ‘inflate’ in specified packages and libraries:
you could try ‘??inflate’`

**Comment by dgrtwo** [comment]
`inflate()` has been deprecated from broom in favor of `tidyr::crossing()`
